.PHONY: clean All

All:
	@echo "----------Building project:[ UOC20242 - Debug ]----------"
	@"$(MAKE)" -f  "UOC20242.mk"
clean:
	@echo "----------Cleaning project:[ UOC20242 - Debug ]----------"
	@"$(MAKE)" -f  "UOC20242.mk" clean
